### ISSUE TITLE
Sync with current PyMySQL

### ISSUE THREAD

**Issue by kesmit13** [nakagami/CyMySQL#34]
This project started as a fork of PyMySQL, but it hasn't been synced in a very long time. Are there any plans to merge the current PyMySQL code in? There are a number of new features that I'd like to see made available.

**Comment by nakagami** [comment]
Thanks for the question.

CyMySQL and PyMySQL are now separate, and PyMySQL is great with the new features it adds.


CyMySQL is going to support Python 2.7 for a while longer.
Therefore, we don't expect to be able to merge PyMySQL features easily.

Mainly because I don't have the time to watch and implement new PyMySQL features, so I can't add PyMySQL features to CyMySQL.

However, I am willing to add any features that are needed, for example CyMySQL support for the new authentication mechanism in MySQL8.
